# Generated by Django 4.0.5 on 2022-07-02 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myResidenceService.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Colony_code', models.CharField(max_length=30)),
                ('Col_name', models.CharField(max_length=30)),
                ('Station', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empno', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=100)),
                ('Desig', models.CharField(max_length=30)),
                ('PAN', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sec_incharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empno', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Desig', models.CharField(max_length=100)),
                ('Level', models.CharField(blank=True, max_length=100)),
                ('Eng_ele', models.CharField(blank=True, max_length=100)),
                ('PAN', models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='SSE_Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empno', models.CharField(max_length=30)),
                ('Colony_code', models.CharField(max_length=30)),
                ('Department', models.CharField(choices=[('Civil', 'Civil'), ('Electrical', 'Electrical'), ('Telnet', 'Telnet')], max_length=30, null=True)),
                ('groupName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepairSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.repair')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qtr_ID', models.CharField(max_length=30)),
                ('Qtr_no', models.CharField(max_length=30)),
                ('Qtr_type', models.CharField(max_length=30)),
                ('Colony_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.colony')),
            ],
        ),
        migrations.CreateModel(
            name='Qtr_occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occ_dt', models.DateField(blank=True, default=None, null=True)),
                ('Vac_dt', models.DateField(blank=True, default=None, null=True)),
                ('Empno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.employee')),
                ('Qtr_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.quarter')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_no', models.CharField(default=myResidenceService.models.increment_booking_number, editable=False, max_length=20)),
                ('Repair_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Complaint_date', models.DateTimeField(auto_now_add=True)),
                ('Complaint_detail', models.CharField(max_length=200)),
                ('Service_status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopen')], default='CREATED', max_length=10)),
                ('Service_detail', models.CharField(blank=True, max_length=20)),
                ('Reopend', models.IntegerField(blank=True, default=0)),
                ('Service_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('Currently_with', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.sse_colony')),
                ('Empno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.employee')),
                ('Qtr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myResidenceService.qtr_occupancy')),
                ('Repair_sub_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myResidenceService.repairsubtype')),
                ('Repair_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myResidenceService.repair')),
            ],
        ),
    ]
