# Generated by Django 3.2.5 on 2021-10-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Colony_code', models.CharField(max_length=20)),
                ('Station', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empno', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('Desig', models.CharField(max_length=20)),
                ('PAN', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SSE_Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empno', models.CharField(max_length=20)),
                ('Colony_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('Empno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Sec_incharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Desig', models.CharField(max_length=100)),
                ('Level', models.CharField(max_length=100)),
                ('Eng_ele', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=11)),
                ('Empno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.sse_colony')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qtr_ID', models.CharField(max_length=20)),
                ('Qtr_no', models.CharField(max_length=20)),
                ('Qtr_type', models.CharField(max_length=20)),
                ('Colony_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.colony')),
            ],
        ),
        migrations.CreateModel(
            name='Qtr_occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occ_dt', models.DateTimeField()),
                ('Vac_dt', models.DateTimeField()),
                ('Empno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.employee')),
                ('Qtr_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.quarter')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_no', models.CharField(max_length=20)),
                ('Repair_id', models.CharField(max_length=20)),
                ('Complaint_date', models.DateTimeField()),
                ('Complaint_detail', models.CharField(max_length=200)),
                ('Service_status', models.CharField(max_length=20)),
                ('Service_detail', models.CharField(max_length=20)),
                ('Service_date', models.DateTimeField()),
                ('Currently_with', models.CharField(max_length=20)),
                ('Empno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.employee')),
                ('Qtr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.quarter')),
            ],
        ),
        migrations.AddField(
            model_name='colony',
            name='Col_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.employee'),
        ),
    ]
