# Generated by Django 3.2.5 on 2021-10-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_details',
            name='Qtr_id',
        ),
        migrations.RemoveField(
            model_name='complaint_details',
            name='id',
        ),
        migrations.AddField(
            model_name='complaint_details',
            name='Qtr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myResidenceService.qtr_occupancy'),
        ),
        migrations.AlterField(
            model_name='colony',
            name='Col_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Complaint_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Complaint_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Currently_with',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Repair_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Service_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Service_detail',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Service_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='qtr_occupancy',
            name='Occ_dt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qtr_occupancy',
            name='Vac_dt',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='sec_incharge',
            name='Empno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sec_incharge',
            name='Eng_ele',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sec_incharge',
            name='Level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sec_incharge',
            name='PAN',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
