# Generated by Django 3.2.5 on 2021-10-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='Col_name',
            field=models.CharField(max_length=20),
        ),
    ]
