# Generated by Django 3.2.5 on 2021-10-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0002_auto_20211024_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtr_occupancy',
            name='Vac_dt',
            field=models.DateField(blank=True),
        ),
    ]
