# Generated by Django 3.2.5 on 2021-10-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0002_alter_colony_col_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_details',
            name='Service_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='CREATED', max_length=10),
        ),
    ]
