# Generated by Django 4.0.5 on 2022-07-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0003_sse_colony_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sse_colony',
            name='Colony_code',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sse_colony',
            name='Empno',
            field=models.CharField(max_length=60),
        ),
    ]
