# Generated by Django 3.2.5 on 2021-10-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0003_alter_complaint_details_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Complaint_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Currently_with',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Service_detail',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
