# Generated by Django 3.2.5 on 2021-10-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0004_auto_20211023_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_details',
            name='Complaint_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
