# Generated by Django 3.2.5 on 2021-10-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0005_alter_complaint_details_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_details',
            name='Repair_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Service_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
