# Generated by Django 4.0.5 on 2022-07-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0005_alter_sse_colony_empno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sse_colony',
            name='Empno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.employee'),
        ),
    ]
