# Generated by Django 3.2.5 on 2021-10-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0005_complaint_details_repair_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_details',
            name='Qtr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myResidenceService.quarter'),
        ),
    ]
