# Generated by Django 4.0.5 on 2022-07-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0006_alter_sse_colony_empno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sse_colony',
            name='Colony_code',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='sse_colony',
            name='Empno',
            field=models.CharField(max_length=60),
        ),
    ]
