# Generated by Django 3.2.5 on 2021-10-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0006_auto_20211023_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sec_incharge',
            name='Eng_ele',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sec_incharge',
            name='Level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sec_incharge',
            name='PAN',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
