# Generated by Django 3.2.5 on 2021-11-06 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0007_alter_complaint_details_qtr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_details',
            name='Currently_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.sec_incharge'),
        ),
    ]
