# Generated by Django 3.2.5 on 2021-10-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0007_auto_20211023_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtr_occupancy',
            name='Occ_dt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qtr_occupancy',
            name='Vac_dt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sec_incharge',
            name='Empno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sse_colony',
            name='Empno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.sec_incharge'),
        ),
    ]
