# Generated by Django 3.2.5 on 2021-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0008_auto_20211024_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sse_colony',
            name='Empno',
            field=models.CharField(max_length=20),
        ),
    ]
