# Generated by Django 4.0.5 on 2022-07-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0008_alter_sse_colony_colony_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sec_incharge',
        ),
    ]
