# Generated by Django 3.2.5 on 2021-12-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0009_alter_complaint_details_currently_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_details',
            name='Complaint_no',
            field=models.AutoField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
