# Generated by Django 4.0.5 on 2023-04-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0009_delete_sec_incharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_details',
            name='Priority',
            field=models.CharField(choices=[('MOSTURGENT', 'Most Urgent'), ('INTERMEDIATE', 'Intemediate'), ('PLANNED', 'Planned')], default='PLANNED', max_length=15),
        ),
    ]
