# Generated by Django 3.2.5 on 2021-10-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0010_auto_20211024_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarter',
            name='id',
        ),
        migrations.AlterField(
            model_name='qtr_occupancy',
            name='Vac_dt',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='Qtr_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
