# Generated by Django 3.2.5 on 2021-10-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0012_rename_qtr_id_complaint_details_qtr_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint_details',
            old_name='Qtr_ID',
            new_name='Qtr_id',
        ),
        migrations.AddField(
            model_name='quarter',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quarter',
            name='Qtr_ID',
            field=models.CharField(max_length=20),
        ),
    ]
