# Generated by Django 3.2.5 on 2021-12-11 07:09

from django.db import migrations, models
import myResidenceService.models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0013_alter_complaint_details_complaint_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_details',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Complaint_no',
            field=models.CharField(default=myResidenceService.models.increment_booking_number, editable=False, max_length=20),
        ),
    ]
