# Generated by Django 3.2.5 on 2021-12-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0014_auto_20211211_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_details',
            name='Reopend',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='Service_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
