# Generated by Django 3.2.5 on 2021-10-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0014_rename_qtr_id_complaint_details_qtr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_details',
            name='Qtr_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myResidenceService.qtr_occupancy'),
        ),
    ]
