# Generated by Django 3.2.5 on 2021-10-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0015_alter_complaint_details_qtr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qtr_occupancy',
            name='id',
        ),
        migrations.RemoveField(
            model_name='quarter',
            name='id',
        ),
        migrations.AlterField(
            model_name='qtr_occupancy',
            name='Qtr_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myResidenceService.quarter'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='Qtr_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
