# Generated by Django 3.2.5 on 2021-12-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0015_auto_20211211_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_details',
            name='Service_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopen')], default='CREATED', max_length=10),
        ),
    ]
