# Generated by Django 3.2.5 on 2021-10-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0017_rename_qtr_id_complaint_details_qtr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_details',
            name='Qtr',
        ),
    ]
