# Generated by Django 3.2.5 on 2021-10-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0018_remove_complaint_details_qtr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colony',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sec_incharge',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sse_colony',
            name='id',
        ),
        migrations.AlterField(
            model_name='colony',
            name='Colony_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Empno',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sec_incharge',
            name='Empno',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sse_colony',
            name='Colony_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
