# Generated by Django 3.2.5 on 2021-10-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0019_auto_20211024_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_details',
            name='Qtr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myResidenceService.qtr_occupancy'),
        ),
    ]
