# Generated by Django 3.2.5 on 2021-10-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0021_alter_complaint_details_qtr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_details',
            name='Qtr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myResidenceService.qtr_occupancy'),
        ),
        migrations.AlterField(
            model_name='qtr_occupancy',
            name='Qtr_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myResidenceService.quarter'),
        ),
    ]
