# Generated by Django 3.2.5 on 2021-10-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myResidenceService', '0023_remove_complaint_details_qtr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarter',
            old_name='Qtr_ID',
            new_name='QuarterQtrID',
        ),
    ]
